# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Dr Rumyana Neykova
tagline: Post-Doc at Imperial College London 
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Since my PhD I have devoted my research efforts to provide solutions that (1) tackle practical
problems (writing safe distributed programs in mainstream languages) and (2) are grounded on a solid theoretical
foundation (a type theory for concurrent processes, called session types). I have shown via industry collaborations,
research prototypes and theories how to design expressive protocol specifications (with particular interest in real-time
and fault-tolerant applications) and how to efficiently verify (and recover) programs at runtime.'

#sidebar links
email: rumi.neykova@gmail.com
linkedin: rumineykova
github: rumineykova
twitter: '@rumi'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
